### ISSUE TITLE
Can we set the default memory usage to 256Mb?

### ISSUE THREAD

**Issue by knolleary** [IBM/node-red-app#14]
A Lite account on IBM Cloud is allowed up to 256Mb memory allocated to CF apps. By default, this starter kit assigns 128Mb which is barely enough for a user to do much. The old boilerplate would assign 256Mb so our users didn't need to be aware of this.

**Comment by jmeis** [comment]
Thanks for the feedback @knolleary! I've opened an internal issue for tracking and will send that over to you.
