### ISSUE TITLE
Node RED dashboard: Stage Failed when Deploying

### ISSUE THREAD

**Issue by jonathanrjpereira** [IBM/node-red-app#19]
I edited the `package.json` file and included the following line: ` "node-red-dashboard": "2.x",` as shown in Step 6 of the [Create a Node-RED starter application](https://developer.ibm.com/tutorials/how-to-create-a-node-red-starter-application/) tutorial.

```
{
    "name": "node-red-app",
    "version": "1.1.1",
    "dependencies": {
        "node-red-dashboard": "2.x",
        "@cloudant/cloudant": "^4.2.2",
        "bcrypt": "^3.0.7",
        "body-parser": "1.x",
        "cfenv": "^1.2.2",
        "express": "4.x",
        "http-shutdown": "1.2.2",
        "node-red": "1.x",
        "node-red-node-cf-cloudant": "0.x",
        "node-red-node-openwhisk": "0.x",
        "node-red-node-watson": "0.x",
        "node-red-nodes-cf-sqldb-dashdb": "0.x"
    },
    "scripts": {
        "start": "node --max-old-space-size=160 index.js --settings ./bluemix-settings.js -v"
    },
    "engines": {
        "node": "12.x"
    }
}
```

![image](https://user-images.githubusercontent.com/10046350/79590244-b8b3bb80-80a4-11ea-87d9-1171146310c4.png)

The error looks something like this:

![image](https://user-images.githubusercontent.com/10046350/79590635-50b1a500-80a5-11ea-81da-a16b7a92369f.png)

Is this caused due to inadequate memory allocation during the Continuous Delivery configuration?
If so, How do I go back to the **Continous Delivery Configuration** and change the **Memory Allocation per Instance**?

**Comment by jonathanrjpereira** [comment]
To change the Memory Allocation:

1. Go to Resources
2. Under Cloud Foundry Apps, Click the App you want to Deploy.
3. The Application Overview will open as shown below.
4. You can increase the memory allocation.

In my case, I increased it to 256MB. Even then it Fails to Deploy and I get the same error

![image](https://user-images.githubusercontent.com/10046350/79592370-e5b59d80-80a7-11ea-9737-0644b25f2735.png)

**Comment by knolleary** [comment]
The error means you have more memory allocated to your apps then your account type allows.

If you have a lite account you are limited to 256mb of memory in total for all of your apps.

**Comment by jonathanrjpereira** [comment]
Is there a way to fix this?

**Comment by knolleary** [comment]
A lite account can only have 256Mb of memory allocated to running applications. If you want to deploy another app, you'll need to stop one of your existing apps first.

The alternative is to upgrade to a standard account. But that doesn't get you more free resources - you will incur a cost to run more then 256mb of apps.

**Comment by jonathanrjpereira** [comment]
I deleted all the apps/services in my resource list. 

I created a new app with a 128MB instance and it deployed successfully.
