### ISSUE TITLE
WebApp Starter Fails to deploy in pipeline

### ISSUE THREAD

**Issue by binnes** [IBM/node-red-app#2]
When deploying using the WebApp starter the deploy pipeline stage fails as it is trying to bind the Cloudant service, but the service name is incorrect in the script configured into the pipeline - do services need to be bound here, as the CF App already has the services bound?

[deploy.log.txt](https://github.com/IBM/node-red-app/files/3271917/deploy.log.txt)

**Comment by jmeis** [comment]
There have been updates to this repo since June, so I'm going to close this issue as stale -- please re-open if this is still a problem.
