### ISSUE TITLE
Deletion of Node-Red Toolchain retains cf route

### ISSUE THREAD

**Issue by mlangeles** [IBM/node-red-app#216]
After manually deleting the tools and services included in the node-red tool chain,
cloud foundry route were retained. 

This was discovered through the recreation of the account with the same hostname.
The error encountered was the host name is already used. Upon trying to delete the space,
the error "CF-AssociationNotEmpty','code':10006" was encountered. 

Manual clean up involves the command ibmcloud cf delete-route $domain --hostname $hostname.

**Comment by nfstein** [comment]
Thanks for the issue, can you give us a little more info. Did you create your cloud foundry app through [this flow](https://cloud.ibm.com/developer/appservice/create-app?defaultDeploymentToolchain=&defaultLanguage=NODE&navMode=starterkits&starterKit=59c9d5bd-4d31-3611-897a-f94eea80dc9f) deployed to a cf toolchain? Were the tools and services deleted from within the running node red app UI or from the ibm toolchain view?
