### ISSUE TITLE
is there a way to upgrade to nodered 1.2.x?

### ISSUE THREAD

**Issue by lu4t** [IBM/node-red-app#36]
I tried several ways, and I am unable to upgrade my node-red instance on ibmcloud cf. I am stuck on 1.1.3.

It looks like the version is hardcoded to:
```
    "name": "node-red-app",
    "version": "1.1.3",
```
on the package.json file.

I tried to follow the "Upgrading the version of Node-RED" on this url: https://nodered.org/docs/getting-started/ibmcloud but it doesn't work.

All I could do was to use a k8 instance instead of a cf app. Too bad is the k8 cluster on a Lite account just works for 30 days. Any help would be appreciated. Open to help as tester and/or contribute if needed.
BR

**Comment by knolleary** [comment]
We need to update those docs as the upgrade process is different with this newer starter kit.

The issue comes with the fact this repo now includes a package-lock.js file. This is pinning the version of Node-RED, rather than picking the latest 1.x available at the time of deploy.

To upgrade your app, you'll have to edit the package.json file and change the `node-red` dependency version to 1.2.6. I think that should override the package-lock file.

**Comment by lu4t** [comment]
Thanks for your answer. I tried it, with no success. Here is what I get on the console:

```

vcap@XXXXXXXXXXXXXXXXXXXXX:~/app$ cat package.json 
{
    "name": "node-red-app",
    "version": "1.2.6",
    "dependencies": {
        "@cloudant/cloudant": "^4.2.4",
        "bcrypt": "^5.0.0",
        "body-parser": "1.x",
        "ibm-cloud-env": "^0",
        "express": "4.x",
        "http-shutdown": "1.2.2",
        "node-red": "1.x",
        "node-red-node-cf-cloudant": "0.x",
        "node-red-node-openwhisk": "0.x",
        "node-red-node-watson": "0.x",
        "node-red-nodes-cf-sqldb-dashdb": "0.x",
        "node-red-contrib-ibm-db2": "0.x"
    },
    "scripts": {
        "start": "node --max-old-space-size=160 index.js --settings ./bluemix-settings.js -v"
    },
    "engines": {
        "node": "12.x"
    }
}
```
it looks like changing `package.json` does not overwrite the content of `package-lock.js` file.

Any other suggestion?

**Comment by knolleary** [comment]
You need to edit the node-red version in the dependencies section. You have edited the top level version number which is the version of *your* application.

**Comment by lu4t** [comment]
this time it worked... it was my fault, thanks for your help!!!
