### ISSUE TITLE
Deploy to IBM Cloud Foundry not working - no cloudant !

### ISSUE THREAD

**Issue by ibmrcruicks** [IBM/node-red-app#58]
fails to provision CloudantDB
fails to include manifest.yml - deployment fails due to exceeded memory - 1.25GB instead of 256MB, no dependency on cloudantNoSQLDB service

fixing memory in Cloud Foundry app view results in deployment, but fails to use Cloudant

```
APP/PROC/WEB | 0 | 13 Apr 14:46:14 - Failed to find the Cloudant URL | Apr 13, 2021, 3:46:14 PM
-- | -- | -- | --
APP/PROC/WEB | 0 | 13 Apr 14:46:14 - Loading application settings | Apr 13, 2021, 3:46:14 PM
APP/PROC/WEB | 0 | 13 Apr 14:46:14 - Starting first-use setup | Apr 13, 2021, 3:46:14 PM
APP/PROC/WEB | 0 | 13 Apr 14:46:14 - Waiting for first-use setup to complete

```
followed by
```

APP/PROC/WEB | 0 | 13 Apr 14:47:31 - [info] Flows file     : /home/vcap/app/.node-red/flows.json | Apr 13, 2021, 3:47:31 PM
-- | -- | -- | --
APP/PROC/WEB | 0 | 13 Apr 14:47:31 - [info] Creating new flow file

```

**Comment by ibmrcruicks** [comment]
stop the app once launched/configured and start again -- all config lost (not  a surprise since it was written to ephemeral local file in node.js runtime instance)

**Comment by youming-lin** [comment]
This is working for me. Do you have repro steps?

```
2021-04-13T15:06:31.98+0000 [APP/PROC/WEB/0] OUT > node --max-old-space-size=160 index.js --settings ./bluemix-settings.js -v
   2021-04-13T15:06:33.36+0000 [APP/PROC/WEB/0] OUT 13 Apr 15:06:33 - Starting Node-RED on IBM Cloud bootstrap
   2021-04-13T15:06:33.36+0000 [APP/PROC/WEB/0] OUT 13 Apr 15:06:33 - Loading bluemix-settings.js
   2021-04-13T15:06:33.48+0000 [APP/PROC/WEB/0] OUT [2021-04-13T15:06:33.483] [INFO] ibm-cloud-env - Initializing with /home/vcap/app/server/config/mappings.json
   2021-04-13T15:06:33.49+0000 [APP/PROC/WEB/0] OUT [2021-04-13T15:06:33.498] [ERROR] ibm-cloud-env - File does not exist /home/vcap/app/server/localdev-config.json
   2021-04-13T15:06:33.49+0000 [APP/PROC/WEB/0] OUT 13 Apr 15:06:33 - Using Cloudant service: cloudant db:prodnoderedcftest prefix:nodered
   2021-04-13T15:06:33.71+0000 [APP/PROC/WEB/0] OUT 13 Apr 15:06:33 - Loading application settings
   2021-04-13T15:06:35.57+0000 [APP/PROC/WEB/0] OUT 13 Apr 15:06:35 - Starting first-use setup
   2021-04-13T15:06:35.59+0000 [APP/PROC/WEB/0] OUT 13 Apr 15:06:35 - Waiting for first-use setup to complete
   2021-04-13T15:06:36.27+0000 [CELL/0] OUT Container became healthy
```

**Comment by ibmrcruicks** [comment]
perhaps I wasn't clear -- This behaviour results when using the `Deploy to IBM Cloud` button in the README.md  of this repo, *not* the Node-RED app starter kit mechanism from  IBM Cloud catalog.
. initial deployment of toolchain goes OK - but with no prompt for Cloudant initialisation/sharing
. deploy stage fails with out of memory error
. application console shows deployment attempted with 1.25GB -- reset to 256MB
. manually rerun deploy stage
. after (very long) deployment process, application loads -- logs indicate NO Cloudant connected - any changes will be lost after a restart
<img width="946" alt="Screenshot 2021-04-21 at 17 51 39" src="https://user-images.githubusercontent.com/25483279/115594236-687dc380-a2cd-11eb-807c-16b95446e1e4.png">
<img width="1098" alt="Screenshot 2021-04-21 at 18 10 24" src="https://user-images.githubusercontent.com/25483279/115594241-69aef080-a2cd-11eb-8990-786c494c42cc.png">
<img width="891" alt="Screenshot 2021-04-21 at 18 09 52" src="https://user-images.githubusercontent.com/25483279/115594242-6a478700-a2cd-11eb-8c09-e4e04e821caf.png">
<img width="819" alt="Screenshot 2021-04-21 at 18 08 56" src="https://user-images.githubusercontent.com/25483279/115594245-6ae01d80-a2cd-11eb-859e-c62790224f6b.png">
<img width="947" alt="Screenshot 2021-04-21 at 17 56 33" src="https://user-images.githubusercontent.com/25483279/115594248-6b78b400-a2cd-11eb-95e7-2dbf8d207ba7.png">
<img width="1283" alt="Screenshot 2021-04-21 at 17 51 52" src="https://user-images.githubusercontent.com/25483279/115594250-6b78b400-a2cd-11eb-8e2e-0c67633aa06a.png">

**Comment by ibmrcruicks** [comment]
looks like standalone `Deploy to IBM Cloud` no longer works as expected 

can this be fixed,  or removed if the inttent is to no longer maintain direct deployment from this repo?

**Comment by youming-lin** [comment]
@jmeis We don't support direct deployments anymore, right? Since `mapping.json` is not generated in this scenario.

**Comment by jmeis** [comment]
I think we can either remove the button from the repo or create a link to the Starter Kit on public cloud.

**Comment by jmeis** [comment]
Replaced the button with a new one that aligns with the other starter kits.

**Comment by ibmrcruicks** [comment]
thanks Joseph!
