### ISSUE TITLE
Cloud Foundry Deployment doesn't work

### ISSUE THREAD

**Issue by thomassuedbroecker** [IBM/node-red-app#62]
**Problem:** Cloud Foundry Deployment doesn't work

**Objective:**
Using IBM Cloud [Node-RED Starter-Kit ](https://cloud.ibm.com/developer/appservice/create-app?starterKit=59c9d5bd-4d31-3611-897a-f94eea80dc9f&defaultLanguage=undefined) to deploy a Node -RED instance to IBM Cloud for a hackathon with an [IBM Cloud Lite Account](https://www.ibm.com/cloud/free).

**What I did:**
I used an empty lite account "no single service was instantiated" on IBM Cloud and followed the steps defined in the Starter-Kit for the App. IBM Cloud region: eu-germany

**Result:**
- The single source repository for the deployment  ended in **cloning three different repositories** into the IBM Cloud GitHub. For example one is called _"tekton catalog"_
- The tekton pipeline never finished any task or step 
- The Node-RED cloud foundry application were never deployed

**Comment by ibmrcruicks** [comment]
just tried the same (using London, as target/destination for all location settings). 
after extraordinarily long time provisioning Cloudant (4-5 minutes), get  the 3 repos in gitlab, 2 pipelines, but only the ci-pipeline populated, which runs automatically, and eventually launches Node-RED initial setup.
You targetted Cloud Foundry as the runtime?

**Comment by thomassuedbroecker** [comment]
> just tried the same (using London, as target/destination for all location settings).
> after extraordinarily long time provisioning Cloudant (4-5 minutes), get the 3 repos in gitlab, 2 pipelines, but only the ci-pipeline populated, which runs automatically, and eventually launches Node-RED initial setup.
> You targetted Cloud Foundry as the runtime?

@ibmrcruicks Yes, it was yesterday at 21:00 CET. I will try it now once more.

**Comment by thomassuedbroecker** [comment]
@ibmrcruicks : Here my feedback

**Result for today at 13:00 CET**

Creation Success

**Time to create total**

It took in total 15 min to create the instance.

**Created Toolchain elements**

- 3 GitHub projects inside IBM Cloud:
   - Tekton Catalog
   - This GitHub Project
   - Pipeline
   
- Delivery Pipeline
  - CI pipeline (Continues integration for this "GitHub Project")
  - PI pipeline (Configurations for in the "Tekton Catalog" "Pipeline" GitHub projects)
 
**IBM Cloud Services created**

- Total created IBM Cloud services are still as documented [here](https://suedbroecker.net/2020/03/09/a-short-introduction-of-the-node-red-starter-kit-on-ibm-cloud-for-hackathons/).

**Comment by thomassuedbroecker** [comment]
It seems it currently works, may it was along yesterday.
