### ISSUE TITLE
Can we have some FAQs

### ISSUE THREAD

**Issue by knobutan** [IBM/node-red-app#66]
Hi team,

Number of new users start off IBM Cloud experience with Node-RED starter app which is great but some users are not too familiar to the platform, so it would be great to have the topology explained and some troubleshooting / FAQ in this page or in the blog (https://developer.ibm.com/components/node-red/tutorials/how-to-create-a-node-red-starter-application/)

I am not too sure if this is a correct place to raise this, but if you can consider adding some explanation on the underlying technologies or minimum requirements, that would help new users to jump start.
- Cloud Foundry space (This is where Node-RED JS app will be deployed)
- Cloudant (Where all Node-RED flow data will go. Will be deployed when you deploy the starter)
- Continuous Delivery service / Toolchain. This is to pull Node-RED code and deploy onto Cloud Foundry

Also, some users reported an issue when setting up the toolchain. I reproduced the issue when selecting CF org / space which I do not have access to. However the error is generic and users will not know where to fix. Also it is coming from the platform (I assume this behavor is hard to change) so can we have troubleshooting section that addresses this issue and guide users to check their CF access?
![image](https://user-images.githubusercontent.com/22388866/116628312-2d952300-a992-11eb-9397-2e4e38852af4.png)

**Comment by jmeis** [comment]
Thanks for the feedback -- we've contacted our doc focal about this.
